.PHONY: clean All

All:
	@echo "----------Building project:[ NMCQuestion - Debug ]----------"
	@cd "NMCQuestion" && "$(MAKE)" -f  "NMCQuestion.mk"
clean:
	@echo "----------Cleaning project:[ NMCQuestion - Debug ]----------"
	@cd "NMCQuestion" && "$(MAKE)" -f  "NMCQuestion.mk" clean
