.PHONY: clean All

All:
	@echo "----------Building project:[ WorkSpaceTemplate - Debug ]----------"
	@cd "WorkSpaceTemplate" && "$(MAKE)" -f  "WorkSpaceTemplate.mk"
clean:
	@echo "----------Cleaning project:[ WorkSpaceTemplate - Debug ]----------"
	@cd "WorkSpaceTemplate" && "$(MAKE)" -f  "WorkSpaceTemplate.mk" clean
